name: Npm check updates action
description: npm package update action using ncu
inputs:
  path:
    description: working directory
    required: false
    default: ''
  package_manager:
    description: which package manager you want to use
    required: false
    default: 'npm'
outputs:
  has_update:
    description: whether update available or not
  formatted_as_json:
    description: new version information formatted as json
  formatted_as_columns:
    description: new version information formatted as columns for markdown table
runs:
  using: node14
  main: dist/index.js

